### PR TITLE
Allow GHC-9.6

### LINKED ISSUE #80: Allow GHC-9.6
Bounds exclude GHC-9.6.1, which has base-4.18. I believe a Hackage revision would be sufficient to allow this.

### PR DESCRIPTION
**Pull request by ysangkok**
Fixes #80.

I have disabled Haddocks on a bunch of GHC versions since there are bugs in Haddock as explained in:
* haskell/text/issues/514

This contains allow-newers that could be removed when these changes are on Hackage:
* well-typed/generics-sop/pull/161
* phadej/insert-ordered-containers/pull/46
* phadej/insert-ordered-containers/issues/50

### CODE REVIEW

**Comment by ysangkok** [comment]
I would very much appreciate a review @maksbotan , if you have time.

**Review by maksbotan — COMMENTED** [review]
cabal-install-3.10 in the recent `haskell-ci` seems to cause too many breakage. can you please revert all changes except `cabal.project` and `openapi3.cabal`?

**Comment by ysangkok** [comment]
I have removed the changes as suggested. But please note that there are [no longer Ubuntu 18.04 runners](https://github.com/actions/runner-images/issues/6002), so CI jobs can't be run any more.

**Comment by ysangkok** [comment]
Added two commits such that Haddocks are run for all GHC versions, but Cabal 3.10.1.0 is only used for the GHC 9.6 build.

**Comment by maksbotan** [comment]
@ysangkok thanks! i've published a revision to hackage. sorry for the delay

will you add 9.6 to `servant-openapi3` as well?

**Pull request merged**
